name: CI/CD - Build, Teste e Deploy na EC2

on:
  push:
    branches:
      - master

jobs:
  build-tests-and-push:
    name: CI - Build e Teste
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0'
          
      - name: Restore dependencies
        run: dotnet Restore
        
      - name: Build solution
        run: dotnet build --configuration Debug
        
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t z4lit0/fiapcloudgamingdockrepo:latest .

      - name: Push Docker image
        run: docker push z4lit0/fiapcloudgamingdockrepo:latest
        
  deploy-to-ec2:
    needs: build-tests-and-push
    name: CD - Deploy na EC2
    runs-on: ubuntu-latest

    steps:
      - name: Deploy na EC2 via SSH
        uses: appleboy/ssh-action@v0.1.9
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ec2-user
          key: ${{ secrets.EC2_SSH_KEY }}
          passphrase: ${{ secrets.EC2_SSH_PASSPHRASE }}
          script: |
            docker pull z4lit0/fiapcloudgamingdockrepo:latest
            docker stop fcg.api || true
            docker rm fcg.api || true
            docker run -d --name fcg.api -p 5001:8080 z4lit0/fiapcloudgamingdockrepo:latest
